use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Vernieuwen",
    update_frequency: "Updatefrequentie",
    one_minute: "1 minuut",
    five_minutes: "5 minuten",
    fifteen_minutes: "15 minuten",
    one_hour: "1 uur",
    codex_model: "Codex",
    settings: "Instellingen",
    start_with_windows: "Opstarten met Windows",
    reset_position: "Positie herstellen",
    language: "Taal",
    system_default: "Systeemstandaard",
    exit: "Afsluiten",
    session_window: "5u",
    weekly_window: "7d",
    now: "nu",
    day_suffix: "d",
    hour_suffix: "u",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Codex-authenticatiefout",
    codex_token_expired_body: "Voer 'codex' uit in een terminal en volg de aanmeldstappen. Ververs of herstart de app daarna.",
    update_title: "Codex Usage Win-update",
    update_checking: "Controleren op updates...",
    update_downloading: "Bijwerken naar",
    update_success: "Bijgewerkt naar",
    update_current: "De nieuwste versie is al geïnstalleerd",
    update_available: "Nieuwe versie beschikbaar",
    update_check_failed: "Controleren op updates is mislukt",
    update_download_failed: "Downloaden van de update is mislukt",
    update_checksum_failed: "Verificatie van het updatebestand is mislukt",
    update_target_not_writable: "De programmamap is niet beschrijfbaar",
    update_helper_failed: "Starten van de updater is mislukt",
};
