use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Refresh",
    update_frequency: "Update Frequency",
    one_minute: "1 Minute",
    five_minutes: "5 Minutes",
    fifteen_minutes: "15 Minutes",
    one_hour: "1 Hour",
    codex_model: "Codex",
    settings: "Settings",
    start_with_windows: "Start with Windows",
    reset_position: "Reset Position",
    language: "Language",
    system_default: "System Default",
    exit: "Exit",
    session_window: "5h",
    weekly_window: "7d",
    now: "now",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Codex Auth Error",
    codex_token_expired_body: "Run 'codex' in a terminal and follow the sign-in prompts. After that, refresh or restart this app.",
    update_title: "Codex Usage Win Update",
    update_checking: "Checking for updates...",
    update_downloading: "Updating to",
    update_success: "Successfully updated to",
    update_current: "Already on the latest version",
    update_available: "New version available",
    update_check_failed: "Failed to check for updates",
    update_download_failed: "Failed to download the update",
    update_checksum_failed: "Update file verification failed",
    update_target_not_writable: "The program directory is not writable",
    update_helper_failed: "Failed to start the updater",
};
