use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Actualiser",
    update_frequency: "Fréquence de mise à jour",
    one_minute: "1 minute",
    five_minutes: "5 minutes",
    fifteen_minutes: "15 minutes",
    one_hour: "1 heure",
    codex_model: "Codex",
    settings: "Paramètres",
    start_with_windows: "Démarrer avec Windows",
    reset_position: "Réinitialiser la position",
    language: "Langue",
    system_default: "Par défaut du système",
    exit: "Quitter",
    session_window: "5h",
    weekly_window: "7d",
    now: "maintenant",
    day_suffix: "j",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Erreur d'authentification Codex",
    codex_token_expired_body: "Executez 'codex' dans un terminal et suivez les instructions de connexion. Ensuite, actualisez ou redemarrez cette application.",
    update_title: "Codex Usage Win - Mise à jour",
    update_checking: "Recherche des mises à jour...",
    update_downloading: "Mise à jour vers",
    update_success: "Mise à jour réussie vers",
    update_current: "Vous utilisez déjà la dernière version",
    update_available: "Nouvelle version disponible",
    update_check_failed: "Échec de la recherche de mises à jour",
    update_download_failed: "Échec du téléchargement de la mise à jour",
    update_checksum_failed: "Échec de la vérification du fichier de mise à jour",
    update_target_not_writable: "Le dossier du programme n'est pas accessible en écriture",
    update_helper_failed: "Échec du démarrage de l'outil de mise à jour",
};
