use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Aktualisieren",
    update_frequency: "Aktualisierungsintervall",
    one_minute: "1 Minute",
    five_minutes: "5 Minuten",
    fifteen_minutes: "15 Minuten",
    one_hour: "1 Stunde",
    codex_model: "Codex",
    settings: "Einstellungen",
    start_with_windows: "Mit Windows starten",
    reset_position: "Position zurücksetzen",
    language: "Sprache",
    system_default: "Systemstandard",
    exit: "Beenden",
    session_window: "5h",
    weekly_window: "7d",
    now: "jetzt",
    day_suffix: "T",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Codex-Authentifizierungsfehler",
    codex_token_expired_body: "Fuhren Sie 'codex' in einem Terminal aus und folgen Sie den Anmeldeanweisungen. Aktualisieren oder starten Sie diese App anschliessend neu.",
    update_title: "Codex Usage Win-Update",
    update_checking: "Suche nach Updates...",
    update_downloading: "Aktualisierung auf",
    update_success: "Erfolgreich aktualisiert auf",
    update_current: "Die neueste Version ist bereits installiert",
    update_available: "Neue Version verfügbar",
    update_check_failed: "Die Suche nach Updates ist fehlgeschlagen",
    update_download_failed: "Das Update konnte nicht heruntergeladen werden",
    update_checksum_failed: "Die Prüfung der Update-Datei ist fehlgeschlagen",
    update_target_not_writable: "Das Programmverzeichnis ist nicht beschreibbar",
    update_helper_failed: "Der Updater konnte nicht gestartet werden",
};
