use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "更新",
    update_frequency: "更新間隔",
    one_minute: "1分",
    five_minutes: "5分",
    fifteen_minutes: "15分",
    one_hour: "1時間",
    codex_model: "Codex",
    settings: "設定",
    start_with_windows: "Windows と同時に開始",
    reset_position: "位置をリセット",
    language: "言語",
    system_default: "システム既定",
    exit: "終了",
    session_window: "5h",
    weekly_window: "7d",
    now: "今",
    day_suffix: "日",
    hour_suffix: "時間",
    minute_suffix: "分",
    second_suffix: "秒",
    codex_token_expired_title: "Codex 認証エラー",
    codex_token_expired_body: "ターミナルで 'codex' を実行し、サインインの案内に従ってください。その後、このアプリを更新または再起動してください。",
    update_title: "Codex Usage Win 更新",
    update_checking: "更新を確認しています...",
    update_downloading: "更新中",
    update_success: "正常に更新しました:",
    update_current: "すでに最新バージョンです",
    update_available: "新しいバージョンがあります",
    update_check_failed: "更新の確認に失敗しました",
    update_download_failed: "更新のダウンロードに失敗しました",
    update_checksum_failed: "更新ファイルの検証に失敗しました",
    update_target_not_writable: "プログラムフォルダーに書き込めません",
    update_helper_failed: "アップデーターの起動に失敗しました",
};
