use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "새로고침",
    update_frequency: "업데이트 주기",
    one_minute: "1분",
    five_minutes: "5분",
    fifteen_minutes: "15분",
    one_hour: "1시간",
    codex_model: "Codex",
    settings: "설정",
    start_with_windows: "Windows 시작 시 자동 실행",
    reset_position: "위치 초기화",
    language: "언어",
    system_default: "시스템 기본값",
    exit: "종료",
    session_window: "5시간",
    weekly_window: "7일",
    now: "지금",
    day_suffix: "일",
    hour_suffix: "시간",
    minute_suffix: "분",
    second_suffix: "초",
    codex_token_expired_title: "Codex 인증 오류",
    codex_token_expired_body: "터미널에서 'codex'를 실행하고 로그인 안내를 따르세요. 그런 다음 이 앱을 새로 고치거나 다시 시작하세요.",
    update_title: "Codex Usage Win 업데이트",
    update_checking: "업데이트 확인 중...",
    update_downloading: "업데이트 중",
    update_success: "성공적으로 업데이트됨:",
    update_current: "이미 최신 버전입니다",
    update_available: "새 버전 사용 가능",
    update_check_failed: "업데이트 확인에 실패했습니다",
    update_download_failed: "업데이트 다운로드에 실패했습니다",
    update_checksum_failed: "업데이트 파일 검증에 실패했습니다",
    update_target_not_writable: "프로그램 폴더에 쓸 수 없습니다",
    update_helper_failed: "업데이터를 시작하지 못했습니다",
};
