use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Atualizar",
    update_frequency: "Frequência de Atualização",
    one_minute: "1 Minuto",
    five_minutes: "5 Minutos",
    fifteen_minutes: "15 Minutos",
    one_hour: "1 Hora",
    codex_model: "Codex",
    settings: "Configurações",
    start_with_windows: "Iniciar com o Windows",
    reset_position: "Redefinir Posição",
    language: "Idioma",
    system_default: "Padrão do Sistema",
    exit: "Sair",
    session_window: "5h",
    weekly_window: "7d",
    now: "agora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Erro de Autenticação do Codex",
    codex_token_expired_body: "Execute 'codex' em um terminal e siga as instruções de login. Depois disso, atualize ou reinicie este aplicativo.",
    update_title: "Codex Usage Win - Atualização",
    update_checking: "Verificando atualizações...",
    update_downloading: "Atualizando para",
    update_success: "Atualizado com sucesso para",
    update_current: "Você já está na versão mais recente",
    update_available: "Nova versão disponível",
    update_check_failed: "Falha ao verificar atualizações",
    update_download_failed: "Falha ao baixar a atualização",
    update_checksum_failed: "Falha na verificação do arquivo de atualização",
    update_target_not_writable: "A pasta do programa não permite gravação",
    update_helper_failed: "Falha ao iniciar o atualizador",
};
