use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Обновить",
    update_frequency: "Частота обновления",
    one_minute: "1 минута",
    five_minutes: "5 минут",
    fifteen_minutes: "15 минут",
    one_hour: "1 час",
    codex_model: "Codex",
    settings: "Настройки",
    start_with_windows: "Запускать вместе с Windows",
    reset_position: "Сбросить позицию",
    language: "Язык",
    system_default: "Системный по умолчанию",
    exit: "Выход",
    session_window: "5ч",
    weekly_window: "7д",
    now: "сейчас",
    day_suffix: "д",
    hour_suffix: "ч",
    minute_suffix: "м",
    second_suffix: "с",
    codex_token_expired_title: "Ошибка авторизации Codex",
    codex_token_expired_body: "Запустите 'codex' в терминале и следуйте инструкциям для входа. После этого обновите или перезапустите приложение.",
    update_title: "Codex Usage Win - Обновление",
    update_checking: "Проверка обновлений...",
    update_downloading: "Обновление до",
    update_success: "Успешно обновлено до",
    update_current: "Уже установлена последняя версия",
    update_available: "Доступна новая версия",
    update_check_failed: "Не удалось проверить обновления",
    update_download_failed: "Не удалось скачать обновление",
    update_checksum_failed: "Не удалось проверить файл обновления",
    update_target_not_writable: "Нет доступа на запись в папку программы",
    update_helper_failed: "Не удалось запустить средство обновления",
};
