use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "立即刷新",
    update_frequency: "刷新频率",
    one_minute: "1 分钟",
    five_minutes: "5 分钟",
    fifteen_minutes: "15 分钟",
    one_hour: "1 小时",
    codex_model: "Codex",
    settings: "设置",
    start_with_windows: "开机自动启动",
    reset_position: "重置位置",
    language: "语言",
    system_default: "跟随系统",
    exit: "退出",
    session_window: "5H",
    weekly_window: "7D",
    now: "现在",
    day_suffix: "天",
    hour_suffix: "小时",
    minute_suffix: "分钟",
    second_suffix: "秒",
    codex_token_expired_title: "Codex 登录已失效",
    codex_token_expired_body: "请在终端中运行 'codex' 并按提示重新登录。完成后请刷新或重启本工具。",
    update_title: "Codex Usage Win 更新",
    update_checking: "正在检查更新…",
    update_downloading: "正在更新到",
    update_success: "已成功更新到",
    update_current: "当前已是最新版本",
    update_available: "发现新版本",
    update_check_failed: "检查更新失败",
    update_download_failed: "下载更新失败",
    update_checksum_failed: "更新文件校验失败",
    update_target_not_writable: "当前程序目录无法写入",
    update_helper_failed: "启动更新程序失败",
};
