use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "Actualizar",
    update_frequency: "Frecuencia de actualización",
    one_minute: "1 minuto",
    five_minutes: "5 minutos",
    fifteen_minutes: "15 minutos",
    one_hour: "1 hora",
    codex_model: "Codex",
    settings: "Configuración",
    start_with_windows: "Iniciar con Windows",
    reset_position: "Restablecer posición",
    language: "Idioma",
    system_default: "Predeterminado del sistema",
    exit: "Salir",
    session_window: "5h",
    weekly_window: "7d",
    now: "ahora",
    day_suffix: "d",
    hour_suffix: "h",
    minute_suffix: "m",
    second_suffix: "s",
    codex_token_expired_title: "Error de autenticacion de Codex",
    codex_token_expired_body: "Ejecuta 'codex' en una terminal y sigue las indicaciones de inicio de sesion. Despues, actualiza o reinicia esta aplicacion.",
    update_title: "Codex Usage Win - Actualización",
    update_checking: "Buscando actualizaciones...",
    update_downloading: "Actualizando a",
    update_success: "Actualizado correctamente a",
    update_current: "Ya tienes la versión más reciente",
    update_available: "Nueva versión disponible",
    update_check_failed: "No se pudo buscar actualizaciones",
    update_download_failed: "No se pudo descargar la actualización",
    update_checksum_failed: "Falló la verificación del archivo de actualización",
    update_target_not_writable: "No se puede escribir en la carpeta del programa",
    update_helper_failed: "No se pudo iniciar el actualizador",
};
