use super::Strings;

pub(super) const STRINGS: Strings = Strings {
    window_title: "Codex Usage Win",
    refresh: "重新整理",
    update_frequency: "更新頻率",
    one_minute: "1 分鐘",
    five_minutes: "5 分鐘",
    fifteen_minutes: "15 分鐘",
    one_hour: "1 小時",
    codex_model: "Codex",
    settings: "設定",
    start_with_windows: "開機時啟動",
    reset_position: "重置位置",
    language: "語言",
    system_default: "系統預設",
    exit: "結束",
    session_window: "5h",
    weekly_window: "7d",
    now: "現在",
    day_suffix: "天",
    hour_suffix: "時",
    minute_suffix: "分",
    second_suffix: "秒",
    codex_token_expired_title: "Codex 驗證錯誤",
    codex_token_expired_body:
        "請在終端機中執行 'codex'，並依照登入提示操作。完成後，請重新整理或重新啟動此應用程式。",
    update_title: "Codex Usage Win 更新",
    update_checking: "正在檢查更新…",
    update_downloading: "正在更新至",
    update_success: "已成功更新到",
    update_current: "目前已是最新版本",
    update_available: "發現新版本",
    update_check_failed: "檢查更新失敗",
    update_download_failed: "下載更新失敗",
    update_checksum_failed: "更新檔案驗證失敗",
    update_target_not_writable: "目前程式目錄無法寫入",
    update_helper_failed: "啟動更新程式失敗",
};
